#define IDC_STATIC               -1
#define IDC_MYICON               2
#define IDD_SIMPLEWIN32_DIALOG   102
#define IDD_ABOUTBOX             103
#define IDS_APP_TITLE            103
#define IDM_ABOUT                104
#define IDM_EXIT                 105
#define IDI_SIMPLEWIN32          107
#define IDI_SMALL                108
#define IDC_SIMPLEWIN32          109
#define IDR_MAINFRAME            128
